apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/component: book-store
  app.openshift.io/runtime: dotnet

resources:
- deployment.yaml
- service.yaml
- route.yaml