apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-store
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"book-store-mongo-prod"}]'
spec:
  replicas: 2