apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: book-store-database
spec:
  generators:
    - git:
        repoURL: https://github.com/clbartolome/bookstore-dotnet-6.git
        revision: master
        files:
          - path: "gitops/configuration/*.json"
  template:
    metadata:
      name: 'book-store-database-{{ environment }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/clbartolome/bookstore-dotnet-6.git
        targetRevision: '{{ argo_config.branch }}'
        path: 'gitops/bookstore-mongo/{{ environment }}'
        helm:
          valueFiles:
            - values.{{ environment }}.yaml
      destination:
        server: '{{ k8s_cluster.address }}'
        namespace: '{{ k8s_cluster.namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true