apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: book-store-app
spec:
  generators:
    - git:
        repoURL: https://github.com/clbartolome/bookstore-dotnet-6.git
        revision: main
        files:
          - path: "cicd-resources/argo/environments/*.json"
  template:
    metadata:
      name: '{{ environment }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/clbartolome/bookstore-dotnet-6.git
        targetRevision: '{{ argo_config.branch }}'
        path: 'gitops/bookstore/overlays/{{ environment }}'
      destination:
        server: '{{ k8s_cluster.address }}'
        namespace: '{{ k8s_cluster.namespace }}'
      syncPolicy:
        automated:
          prune: '{{ argo_config.prune }}'
          selfHeal: '{{ argo_config.selfHeal }}'