apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

resources:
- bc.yaml
- is.yaml

nameSuffix: -dev

commonLabels:
  app: book-store-dev
  app.kubernetes.io/version: "5.7.21"
  app.kubernetes.io/instance: book-store-dev
  app.kubernetes.io/part-of: book-store-dev

patches:
- ./deployment.yaml

configMapGenerator:
- name: book-store
  files:
  - application.properties

secretGenerator:
- name: book-store
  envs:
  - secured.properties

images:
- name: bookstore
  newName: image-registry.openshift-image-registry.svc:5000/book-store-dev/book-store-dev
  newTag: latest